--CREATE SCHEMA IF NOT EXISTS DB2CRV AUTHORIZATION sa;
CREATE SCHEMA IF NOT EXISTS sistema AUTHORIZATION sa;

CREATE TABLE IF NOT EXISTS sistema.USUARIOS (
   id INT NOT NULL,
   nome VARCHAR(100) NOT NULL,
   nascimento DATE,
   PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS sistema.FUNCIONARIO (
   id INT NOT NULL,
   nome VARCHAR(100) NOT NULL,
   nivelDeAcesso INT NOT NULL,
   email VARCHAR(50) NOT NULL,
   senha VARCHAR(20) NOT NULL,
   PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS sistema.COMPRA (
   id INT NOT NULL,
   nomeProduto VARCHAR(100) NOT NULL,
   valorCompra FLOAT NOT NULL,
   descricao VARCHAR(100) NOT NULL,
   PRIMARY KEY (id)
);



